"use client";
import {useMemo,useState} from "react";
import {Check,Clock3,Eye,FileText,History,MoreHorizontal,Plus,Send,Archive,RotateCcw,Search} from "lucide-react";
import {demoContent,ContentRecord,WorkflowStatus,workflowActions,workflowLabel} from "@/lib/cms-workflow";
export default function ContentStudio(){
 const [items,setItems]=useState<ContentRecord[]>(demoContent),[selected,setSelected]=useState<ContentRecord|null>(demoContent[0]),[query,setQuery]=useState(""),[filter,setFilter]=useState<"all"|WorkflowStatus>("all"),[saved,setSaved]=useState(false);
 const rows=useMemo(()=>items.filter(x=>(filter==="all"||x.status===filter)&&(x.title.toLowerCase().includes(query.toLowerCase())||x.type.toLowerCase().includes(query.toLowerCase()))),[items,filter,query]);
 function update(patch:Partial<ContentRecord>){if(!selected)return;const next={...selected,...patch,updatedAt:new Date().toISOString().slice(0,10)};setSelected(next);setItems(xs=>xs.map(x=>x.id===next.id?next:x));}
 function transition(next:WorkflowStatus){update({status:next,revisions:[...selected!.revisions,{id:"r-"+Date.now(),version:selected!.revisions.length+1,status:next,author:"Current user",createdAt:new Date().toISOString().slice(0,10),summary:workflowLabel(next)}]});}
 return <div className="studio-shell"><header className="studio-head"><div><p className="eyebrow">CONTENT STUDIO</p><h1>Stories & publishing</h1><p>Write, review, schedule and audit every public story from one workspace.</p></div><button className="cms-primary-button"><Plus size={16}/> New content</button></header>
 <div className="studio-toolbar"><div className="studio-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search content..." /></div>{(["all","draft","review","approved","published","scheduled","archived"] as const).map(s=><button key={s} className={filter===s?"active":""} onClick={()=>setFilter(s)}>{s==="all"?"All":workflowLabel(s)}</button>)}</div>
 <div className="studio-layout"><section className="studio-list">{rows.map(item=><button className={"studio-row "+(selected?.id===item.id?"selected":"")} key={item.id} onClick={()=>setSelected(item)}><span className="studio-icon"><FileText size={17}/></span><span className="studio-row-copy"><strong>{item.title}</strong><small>{item.type} · {item.author}</small></span><span className={"workflow-pill "+item.status}>{workflowLabel(item.status)}</span></button>)}</section>
 {selected&&<section className="studio-editor"><div className="editor-top"><div><span className={"workflow-pill "+selected.status}>{workflowLabel(selected.status)}</span><h2>{selected.title}</h2><small>/{selected.slug}</small></div><button><Eye size={16}/> Preview</button></div>
 <label>Title<input value={selected.title} onChange={e=>update({title:e.target.value})}/></label><label>Excerpt<textarea value={selected.excerpt} onChange={e=>update({excerpt:e.target.value})}/></label><label>Body<textarea className="body-field" value={selected.body} onChange={e=>update({body:e.target.value})}/></label>
 <details className="editor-section"><summary>SEO & social metadata</summary><label>SEO title<input value={selected.seoTitle} onChange={e=>update({seoTitle:e.target.value})}/></label><label>Meta description<textarea value={selected.seoDescription} onChange={e=>update({seoDescription:e.target.value})}/></label></details>
 <details className="editor-section"><summary><History size={15}/> Revision history ({selected.revisions.length})</summary><div className="revision-list">{[...selected.revisions].reverse().map(r=><div className="revision" key={r.id}><strong>v{r.version} · {workflowLabel(r.status)}</strong><small>{r.author} · {r.createdAt}</small><span>{r.summary}</span></div>)}</div></details>
 <div className="editor-footer"><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1400)}}>{saved?"Saved":"Save draft"}</button><div className="workflow-actions">{workflowActions(selected.status).map(a=><button key={a.next} onClick={()=>transition(a.next)}>{a.next==="published"?<Check size={15}/>:a.next==="scheduled"?<Clock3 size={15}/>:a.next==="archived"?<Archive size={15}/>:a.next==="draft"?<RotateCcw size={15}/>:<Send size={15}/>} {a.label}</button>)}</div></div>
 </section>}</div></div>;
}