"use client";
import { useMemo, useState } from "react";
import { FileText, PlaySquare, Search, Upload, X } from "lucide-react";
import { mediaAssets, MediaType } from "@/lib/media";
type Filter="all"|MediaType;
export default function AdminMediaPage(){
 const [filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[selected,setSelected]=useState<string|null>(null);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return mediaAssets.filter(a=>(filter==="all"||a.type===filter)&&(!q||[a.title,a.filename,...a.tags].join(" ").toLowerCase().includes(q)));},[filter,query]);
 const current=mediaAssets.find(a=>a.id===selected);
 return <div className="cms-shell"><aside className="cms-sidebar"><div className="cms-brand">BEGAIMEDER <span>CMS</span></div><nav className="cms-nav"><a href="/admin">Overview</a><a href="/admin/content">Content Studio</a><a className="active" href="/admin/media">Media Library</a><a href="/admin">Settings</a><a href="/">View website</a></nav></aside><main className="cms-main"><header className="cms-topbar"><div><p className="eyebrow">MEDIA OPERATIONS</p><h1>Media Library</h1><p>Manage images, video, documents, albums, metadata and publishing readiness.</p></div><button className="cms-primary-button"><Upload size={17}/> Upload media</button></header><section className="media-admin-toolbar"><div className="media-filter-tabs">{(["all","image","video","document"] as Filter[]).map(item=><button className={filter===item?"active":""} key={item} onClick={()=>setFilter(item)}>{item==="all"?"All":item==="image"?"Images":item==="video"?"Videos":"Documents"}</button>)}</div><label className="media-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search media..."/></label></section><section className="upload-dropzone"><Upload size={28}/><div><strong>Drop files here to prepare an upload</strong><span>Images, MP4 video and PDF documents • storage integration comes next</span></div></section><section className="media-admin-grid">{filtered.map(asset=><button className="media-admin-card" key={asset.id} onClick={()=>setSelected(asset.id)}><div className="media-admin-thumb">{asset.type==="image"&&<img src={asset.url} alt=""/>}{asset.type==="video"&&<><img src={asset.thumbnailUrl} alt=""/><span className="media-type-icon"><PlaySquare size={20}/></span></>}{asset.type==="document"&&<span className="document-icon"><FileText size={34}/></span>}</div><div className="media-admin-card-copy"><strong>{asset.title}</strong><span>{asset.filename}</span><small>{asset.size} · {asset.visibility}</small></div></button>)}</section>{current&&<div className="media-inspector-backdrop" onClick={()=>setSelected(null)}><aside className="media-inspector" onClick={e=>e.stopPropagation()}><button className="inspector-close" onClick={()=>setSelected(null)} aria-label="Close"><X size={20}/></button><p className="eyebrow">ASSET INSPECTOR</p><h2>{current.title}</h2>{current.type==="image"&&<img src={current.url} alt={current.alt} className="inspector-preview"/>}<dl className="inspector-details"><div><dt>File</dt><dd>{current.filename}</dd></div><div><dt>Type</dt><dd>{current.mime}</dd></div><div><dt>Size</dt><dd>{current.size}</dd></div><div><dt>Alt text</dt><dd>{current.alt}</dd></div><div><dt>Consent</dt><dd>{current.consentStatus}</dd></div><div><dt>Status</dt><dd>{current.status}</dd></div></dl></aside></div>}</main></div>;
}
