<?php
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ContentController;
use App\Http\Controllers\Api\PageController;
use App\Http\Controllers\Api\MediaController;
use App\Http\Controllers\Api\EventController;
use App\Http\Controllers\Api\AdminController;
use App\Http\Controllers\Api\FormSubmissionController;
use App\Http\Controllers\Api\MediaAlbumController;
use App\Http\Controllers\Api\RevisionController;
use Illuminate\Support\Facades\Route;
Route::prefix('v1')->middleware('throttle:api')->group(function(){
 Route::post('/auth/login',[AuthController::class,'login'])->middleware('throttle:auth');
 Route::post('/auth/forgot-password',[AuthController::class,'forgotPassword'])->middleware('throttle:auth');
 Route::post('/auth/reset-password',[AuthController::class,'resetPassword'])->middleware('throttle:auth');
 Route::post('/auth/logout',[AuthController::class,'logout'])->middleware('auth:sanctum');
 Route::get('/auth/me',[AuthController::class,'me'])->middleware('auth:sanctum');
 Route::get('/auth/email/verify/{id}/{hash}',[AuthController::class,'verifyEmail'])->middleware(['auth:sanctum','signed'])->name('verification.verify');
 Route::get('/pages/{slug}',[PageController::class,'show']);
 Route::get('/content',[ContentController::class,'index']);
 Route::get('/content/{slug}',[ContentController::class,'show']);
 Route::get('/events',[EventController::class,'index']);
 Route::get('/albums',[MediaAlbumController::class,'index']);
 Route::get('/albums/{slug}',[MediaAlbumController::class,'show']);
 Route::post('/forms',[FormSubmissionController::class,'store'])->middleware('throttle:api');
 Route::middleware('auth:sanctum')->group(function(){
  Route::apiResource('pages',PageController::class)->except(['show']);
  Route::apiResource('content',ContentController::class)->except(['index','show']);
  Route::apiResource('media',MediaController::class)->except(['show']);
  Route::apiResource('events',EventController::class)->except(['index']);
  Route::get('/media/{media}/download',[MediaController::class,'download']);
  Route::post('/auth/2fa/setup',[AuthController::class,'setupTwoFactor']);
  Route::post('/auth/2fa/confirm',[AuthController::class,'confirmTwoFactor']);
  Route::post('/auth/2fa/disable',[AuthController::class,'disableTwoFactor']);
  Route::get('/admin/users',[AdminController::class,'users']);
  Route::get('/admin/roles',[AdminController::class,'roles']);
  Route::get('/admin/permissions',[AdminController::class,'permissions']);
  Route::get('/admin/settings',[AdminController::class,'settings']);
  Route::put('/admin/settings/{key}',[AdminController::class,'updateSetting']);
  Route::get('/admin/audit-logs',[AdminController::class,'audit']);
  Route::apiResource('albums',MediaAlbumController::class)->except(['index','show']);
  Route::post('/albums/{album}/media',[MediaAlbumController::class,'attach']);
  Route::get('/revisions/{type}/{id}',[RevisionController::class,'index']);
  Route::get('/revisions/{revision}',[RevisionController::class,'show']);
  Route::post('/revisions/{revision}/restore',[RevisionController::class,'restore']);
  Route::get('/admin/forms',[FormSubmissionController::class,'index']);
  Route::patch('/admin/forms/{submission}',[FormSubmissionController::class,'update']);
 });
});