export type WorkflowStatus="draft"|"review"|"approved"|"published"|"scheduled"|"archived";
export type AuditAction="created"|"updated"|"submitted"|"approved"|"published"|"scheduled"|"archived"|"restored";
export type Revision={id:string;version:number;status:WorkflowStatus;author:string;createdAt:string;summary:string};
export type ContentRecord={id:string;title:string;type:"Story"|"News"|"Announcement"|"Achievement"|"Event";status:WorkflowStatus;slug:string;excerpt:string;body:string;author:string;updatedAt:string;publishAt?:string;seoTitle:string;seoDescription:string;revisions:Revision[]};
export const workflowOrder:WorkflowStatus[]=["draft","review","approved","published","scheduled","archived"];
export const workflowLabel=(s:WorkflowStatus)=>({draft:"Draft",review:"In review",approved:"Approved",published:"Published",scheduled:"Scheduled",archived:"Archived"}[s]);
export const workflowActions=(status:WorkflowStatus):{label:string;next:WorkflowStatus}[]=>({draft:[{label:"Submit for review",next:"review"}],review:[{label:"Approve",next:"approved"}],approved:[{label:"Publish now",next:"published"},{label:"Schedule",next:"scheduled"}],published:[{label:"Archive",next:"archived"}],scheduled:[{label:"Publish now",next:"published"},{label:"Archive",next:"archived"}],archived:[{label:"Restore to draft",next:"draft"}]}[status]);
export const demoContent:ContentRecord[]=[
{id:"story-1",title:"Science Project Showcase",type:"Story",status:"published",slug:"science-project-showcase",excerpt:"Students turn curiosity into hands-on discovery.",body:"A showcase of student-led science projects.",author:"Content Editor",updatedAt:"2026-09-24",seoTitle:"Science Project Showcase | BEGAIMEDER ACADEMY",seoDescription:"Student science projects at BEGAIMEDER ACADEMY.",revisions:[{id:"r1",version:3,status:"published",author:"Content Editor",createdAt:"2026-09-24",summary:"Published final copy"}]},
{id:"news-1",title:"Academic Year 2026 Welcome",type:"News",status:"review",slug:"academic-year-2026-welcome",excerpt:"A new year of learning begins.",body:"Welcome to the new academic year.",author:"Communications Officer",updatedAt:"2026-09-23",seoTitle:"Academic Year 2026 | BEGAIMEDER ACADEMY",seoDescription:"Academic year news and updates.",revisions:[{id:"r2",version:2,status:"review",author:"Communications Officer",createdAt:"2026-09-23",summary:"Updated announcement details"},{id:"r3",version:1,status:"draft",author:"Contributor",createdAt:"2026-09-22",summary:"Initial draft"}]},
{id:"event-1",title:"Parent Community Day",type:"Event",status:"scheduled",slug:"parent-community-day",excerpt:"Families gather for a day of connection.",body:"Parent community activities and school updates.",author:"Admissions Officer",updatedAt:"2026-09-20",publishAt:"2026-10-03T09:00",seoTitle:"Parent Community Day",seoDescription:"Parent community event at BEGAIMEDER ACADEMY.",revisions:[{id:"r4",version:4,status:"scheduled",author:"Admissions Officer",createdAt:"2026-09-20",summary:"Scheduled for publication"}]}
];