<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('roles',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->timestamps();});
  Schema::create('permissions',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->timestamps();});
  Schema::create('role_user',function(Blueprint $t){$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->primary(['role_id','user_id']);});
  Schema::create('permission_role',function(Blueprint $t){$t->foreignId('permission_id')->constrained()->cascadeOnDelete();$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->primary(['permission_id','role_id']);});
  Schema::create('pages',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->string('status')->default('draft')->index();$t->string('template')->default('default');$t->json('seo')->nullable();$t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('published_at')->nullable();$t->timestamp('scheduled_for')->nullable()->index();$t->timestamps();});
  Schema::create('page_blocks',function(Blueprint $t){$t->id();$t->foreignId('page_id')->constrained()->cascadeOnDelete();$t->string('type');$t->unsignedInteger('sort_order')->default(0);$t->json('data');$t->boolean('is_visible')->default(true);$t->timestamps();$t->index(['page_id','sort_order']);});
  Schema::create('contents',function(Blueprint $t){$t->id();$t->string('type')->index();$t->string('title');$t->string('slug')->unique();$t->text('excerpt')->nullable();$t->longText('body');$t->string('status')->default('draft')->index();$t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('reviewer_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('published_at')->nullable()->index();$t->timestamp('scheduled_for')->nullable()->index();$t->json('seo')->nullable();$t->boolean('featured')->default(false);$t->timestamps();});
  Schema::create('events',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->text('excerpt')->nullable();$t->longText('description')->nullable();$t->timestamp('starts_at')->index();$t->timestamp('ends_at')->nullable();$t->string('location')->nullable();$t->string('status')->default('draft')->index();$t->boolean('featured')->default(false);$t->json('seo')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('media_assets',function(Blueprint $t){$t->id();$t->string('title');$t->string('type');$t->string('disk');$t->string('path');$t->string('mime_type');$t->unsignedBigInteger('size');$t->string('visibility')->default('private')->index();$t->string('status')->default('ready');$t->string('alt_text')->nullable();$t->text('caption')->nullable();$t->string('consent_status')->default('not_required');$t->json('metadata')->nullable();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['type','visibility']);});
  Schema::create('revisions',function(Blueprint $t){$t->id();$t->morphs('revisionable');$t->unsignedInteger('version');$t->json('snapshot');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->string('change_summary')->nullable();$t->timestamps();$t->unique(['revisionable_type','revisionable_id','version']);});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action')->index();$t->nullableMorphs('auditable');$t->ipAddress('ip_address')->nullable();$t->text('user_agent')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['created_at','action']);});
  Schema::create('settings',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->json('value')->nullable();$t->string('group')->default('general')->index();$t->boolean('is_public')->default(false);$t->timestamps();});
  Schema::create('form_submissions',function(Blueprint $t){$t->id();$t->string('type')->index();$t->string('name');$t->string('email')->nullable();$t->string('phone')->nullable();$t->json('payload');$t->string('status')->default('new')->index();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->text('notes')->nullable();$t->timestamps();});
 }
 public function down():void{foreach(['form_submissions','settings','audit_logs','revisions','media_assets','events','contents','page_blocks','pages','permission_role','role_user','permissions','roles'] as $table)Schema::dropIfExists($table);}
};