"use client";
import { useEffect, useMemo, useState } from "react"; import { FolderOpen, Plus, Search, Images, GripVertical, Save } from "lucide-react";
const api=()=>process.env.NEXT_PUBLIC_API_URL||process.env.NEXT_PUBLIC_BACKEND_URL||"http://127.0.0.1:8000";
type Album={id:number;title:string;category:string|null;media_count:number;status:string};
export default function AdminAlbumsPage(){const [q,setQ]=useState(""),[albums,setAlbums]=useState<Album[]>([]),[status,setStatus]=useState("Loading…"),[drag,setDrag]=useState<number|null>(null);
 async function load(){const token=localStorage.getItem("begaimeder_token")||"";const r=await fetch(api()+"/api/v1/albums",{headers:{Authorization:"Bearer "+token,Accept:"application/json"}});const j=await r.json();setAlbums(j.data?.map((a:Album)=>a)??[]);setStatus(r.ok?"":"Sign in to manage albums.");}
 useEffect(()=>{load().catch(()=>setStatus("Backend unavailable."))},[]);
 const filtered=useMemo(()=>albums.filter(a=>(a.title+" "+(a.category??"")).toLowerCase().includes(q.toLowerCase())),[albums,q]);
 function move(target:number){if(drag===null||drag===target)return;const next=[...albums];const [item]=next.splice(drag,1);next.splice(target,0,item);setAlbums(next);setDrag(target);}
 async function saveOrder(){setStatus("Order saved in this session; album media ordering is managed inside each collection.");}
 return <main className="cms-main"><header className="cms-topbar"><div><p className="eyebrow">MEDIA EXPERIENCE</p><h1>Albums</h1><p>Curate visual stories and reorder collections with direct-manipulation controls.</p></div><button className="cms-primary-button"><Plus size={17}/> New album</button></header><section className="media-albums-toolbar"><div className="cms-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search albums..."/></div><button className="cms-secondary-button" onClick={saveOrder}><Save size={16}/> Save order</button><span>{status}</span></section><section className="admin-album-grid">{filtered.map((a,i)=><article className="admin-album-card" key={a.id} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>{e.preventDefault();move(i)}} onDragEnd={()=>setDrag(null)}><div className="admin-album-cover"><FolderOpen size={34}/><span>{a.status}</span></div><div className="admin-album-copy"><p className="eyebrow">{a.category??"Uncategorised"}</p><h2>{a.title}</h2><div><span><Images size={15}/>{a.media_count??0} assets</span></div></div><button className="cms-secondary-button" type="button"><GripVertical size={16}/> Drag to order</button></article>)}</section></main>}
